remote_theme: daviddarnes/alembic@main

plugins:
- jekyll-remote-theme

title: GM Fingerprints
description: Some basic examples of client interfaces to ...(Todo-make my proj page)

author:
  name: Hayley Song (@cocoaaa)
